### ISSUE TITLE
Does Matlab system(mkdir) work under Windows?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#122]
Hello all,

I would like to change aas_makedir.m to use system(mkdir) instead of calling mkdir( ) directly (there is a bug in mkdir that breaks aa on our cluster, and I need system(mkdir) as a work-around). However, I don't have a Windows box to test this. Can anyone confirm system(mkdir) works under Windows before I upload my new version into the repository?

Thanks much,
Mike

**Comment by tiborauer** [comment]
Yes, it works under Windows.

**Comment by jooh** [comment]
Hi Mike,

If the idea is to work around a bug on your cluster (rather than a bug with AA itself), it might be better to make a custom 'mkdir' function and deploy it to your cluster instead of changing default AA behaviour for everyone else.

For instance, here at CBU we over-ride the built-in 'copyfile' function for weird cluster storage reasons. Just place a custom version under ~/matlab/ and it should take precedence over the builtin.

**Comment by jones-michael-s** [comment]
Thanks everyone for a quick reply!

Johan -- that might be a quicker solution (there's modules that call mkdir instead of aas_makedir, so changing aas_makedir wouldn't be the end of my problems). 

I've tried it and it works, but Matlab displays a warning (because mkdir is a built-in). Do you have this same issue with copyfile? Is there some way to stop the warning?

**Comment by jooh** [comment]
Not that I know of. But it should only appear once on startup.

**Comment by tiborauer** [comment]
Yes, we always have such warnings:
```
Warning: Function /hpc-software/matlab/cbu/copyfile.m has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict. 
> In path at 110
  In startup at 19
  In matlabrc at 202 
```
