### ISSUE TITLE
Proposed change to aas_runFScommand.m

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#132]
Hello all, 

Running FreeSurfer through aa was crashing on our system, and I tracked the problem to aas_runFScommand.m. The hardcoded ENV variables for Perl 5 are not valid for us. Removing them fixed the problem. That is, I changed

```
ENV = {...
    'PATH',pth;...
    'SUBJECTS_DIR',getenv('SUBJECTS_DIR');...
    'FREESURFER_HOME',aap.directory_conventions.freesurferdir;...
    'FSF_OUTPUT_FORMAT','nii.gz';...
    'MATLABPATH',aap.directory_conventions.spmdir;...
    'MNI_PERL5LIB', fullfile(aap.directory_conventions.freesurferdir, 'mni/lib/perl5/5.8.5');...
    'PERL5LIB', fullfile(aap.directory_conventions.freesurferdir, 'mni/lib/perl5/5.8.5')...
    };
```

to

```
ENV = {...
    'PATH',pth;...
    'SUBJECTS_DIR',getenv('SUBJECTS_DIR');...
    'FREESURFER_HOME',aap.directory_conventions.freesurferdir;...
    'FSF_OUTPUT_FORMAT','nii.gz';...
    'MATLABPATH',aap.directory_conventions.spmdir;...
    };
```

Furthermore, I believe setting these environment variables here is wrong -- FreeSurfer sets proper values in FreeSurferEnv.sh, which gets run when aamod_freesurfer_initialise is called. Setting them here is at best unnecessary.

I suspect what has happened is the current code in aas_runFScommand.m works for whoever wrote it (and still does) but not for people who are using a more recent version of FreeSurfer or who are using it on a system that isn't Linux (read: us). 

The question then is: Does my suggested fix work for everyone? If so, I could push it to the repo.

Thanks much,
Mike

**Comment by tiborauer** [comment]
Hi,

You may be right; however, it must be a linux vs mac difference rather than overfitting to certain system, because it works for more unix systems! In most cases we do not even call FreeSurferEnv.sh (it is empty in aap_parameters_defaults_CBSU/CUSACKLAB/RHUL). Perhaps we can try relying on it rather than setting here manualy.
I will try and let you know.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by tiborauer** [comment]
I have tested both at the CBSU and the RHUL, and it works without explicitly adding PERL environmental variables. So go ahead with the PR! I recommend submitting it from another branch, so that it can be merged independently from your PR with the LI toolbox.

**Comment by jones-michael-s** [comment]
Thanks Tibor. Will do soon...

**Comment by jones-michael-s** [comment]
I did a PR on a new branch containing just a change to aas_runFScommand.m and git wants to merge ALL of the changes in my fork in this new PR (the LI stuff, etc). Is there a way around this? Do I need the "cherry pick" command?

(I deleted the new PR.)

**Comment by tiborauer** [comment]
I think, the easiest way is to have a branch without your other commits, modify aas_runFScommand, and submit a PR.

**Comment by jones-michael-s** [comment]
I added this to my latest PR -- closing the issue...
