### ISSUE TITLE
Documentation: aas_add_special_session

### ISSUE THREAD

**Issue by jooh** [rhodricusack/automaticanalysis#155]
I find this function absolutely baffling. Clearly it does some clever renaming (and also removal?) of streams to handle special data types (e.g. MTR). It would be very helpful if this function had a bit of documentation up top explaining what it does, perhaps with an example.

**Comment by tiborauer** [comment]
I agree and it is my fault, because I re-defined special session/series. My motivation was to avoid the necessity to define new session/series for ASL, MTI, MPM, etc; especially because they are usually acquired onece per subject.
So the curent 'model' is this:
- all special acquisition are treated as one special session/series (therfore they can be processed in parallel)
- the default '*specialseries' streams will be renamed to match the actual series. E.g.: dicom_specialseries --> dicom_ASL; specialseries --> ASL; specialseries_dicom_header --> ASL_dicom_header
- in case of more than one special series, new streams will be appended
Everything is under the hood, and aa_user_ASL , aa_user_ASL, aa_user_MPM, aa_user_MTI are the examples.

**Comment by tiborauer** [comment]
How about adding this to the beginning of  aas_add_special_session:

```
% Add a special session (e.g. ASL, MPM, MTI), which are not explicitly defined, to the analysis. These acquisitions are typically conducted once per subject, hence they are not really multiple sessions (of the same acquisition).
% However, they are independent from each other and therfore can be analyzed in parallel. The function can be called multiple times to add more kinds or more of the same kind; however, the 'session' names must be unique in any 
% case. Example useage can be seen in aa_user_ASL, aa_user_MPM and aa_user_MTI.
%
% FORMAT function aap = aas_add_special_session(aap, name)
% This will add a new special session as specified in the name. Also, the input/output streams of the corresponding processing modules (aamod_get_dicom_specialseries and aamod_convert_specialseries) will be created to match the
% actual series. E.g.: aap=aas_add_special_session(aap,'ASL'); results in streams called dicom_ASL, ASL and ASL_dicom_header.
%
% aap           - aap structure with parameters and tasklist
% name          - name of the session for future reference
```

**Comment by jooh** [comment]
Looks great! Makes sense to me now.

**Comment by tiborauer** [comment]
Added in PR158

**Comment by tiborauer** [comment]
PR158 is just documentation, so it could be perhaps merged without testing, and this issue could be closed, too.

**Comment by jooh** [comment]
I agree that documentation changes can be pushed in without pull requests. It would be great if we can get more quick fixes here without getting stuck in a review process.

Although since I saw this one, could you put the documentation on top of the first line of code ('function ...')  instead of below it please? :)

**Comment by tiborauer** [comment]
No problem! However, it also means that I/we may need to change location of documentations of other functions (e.g. aas_addsubject). I followed the example of SPM, where help is put below the function header.

I have no personal preference, though.

**Comment by jooh** [comment]
Actually, I think you're right. Apparently in Matlab it's convention to put documentation below the header. Mind blown. Sorry - leave it as is.

https://uk.mathworks.com/help/matlab/matlab_prog/add-help-for-your-program.html
