### ISSUE TITLE
Nonprinting characters are now sprinkled throughout the repo

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#170]
Have started encountering non-printing whitespace characters in files recently.

For example, open amod_firstlevel_model.xml in vi and you should see a unicode FEFF before the inputstreams tag.

These appear to be harmless to Matlab, but they create problems with git. I've found some files that have a windows carriage return(^M) appended to the end of every line. As such, it's impossible to change anything in the file without it being a merge conflict, because git thinks *every* line in the file has been changed.

Perhaps this is related to the recent dos2unix commit?

M

**Comment by jooh** [comment]
Hi Mike, this is a long-standing problem with AA and is caused by editing using the Matlab GUI editor in Windows. A lot of the original AA modules appear to have been developed this way, so there's quite a lot of files that have ended up with mixed line breaks.

The idea with that dos2unix commit was to tidy things up. But it's possible that it didn't work perfectly. If you have a better way to get the carriage returns consistent that would be great. We only support unix-based OS so there's no reason to have any Windows carriage returns.

Either way though, you should not encounter merge conflicts as a result of this, unless you have your editor set up to automatically convert all the lines when you save (in which case you might be committing bigger changes than you realise).

**Comment by jones-michael-s** [comment]
Hi Johan,

Thanks for the info. I've looked into this a bit more having a better understanding of things. It looks like dos2unix _mostly_ worked but there's still a few problem files. Grepping around the current repo (`grep -c '\r' *`) turns up a handful of files with ^M and `grep '\x{FEFF}' *.xml` turns up a few headers with FEFF unicode. (Helpful hint: the unicode will show up in vanilla vi, but you need to use a -b switch to see the ^M).

I could edit the stragglers by hand and PR (although I'd like to get my current PR approved before submitting another). Unless someone else would like to volunteer :-)
