### ISSUE TITLE
NIfTI input data format

### ISSUE THREAD

**Issue by giuseppecabras** [rhodricusack/automaticanalysis#82]
Dear Rhodri,
I need your help again! I would like to use data already in NIfTI but I havn't found instructions or examples to do so and I have, for example, T1 and EPI converted NIfTI files ready for an fMRI pipeline. I read in your paper that I can use the aas_addinitialstream command, but I don't know how.
Cheers,
Giuseppe

**Comment by giuseppecabras** [comment]
Hi,
following the help aas_addinitialstream  and some try/error loops, I found that this work in my basic user script: with my aap_tasklist_fmri_fromnifti.xml
% The subject
aap=aas_addsubject(aap,'PUD400614',{'31147_MRI_rsMRI_400614.nii','31148_MRI_sMRI_400614.nii'});
aap=aas_addinitialstream(aap,'structural','PUD400614','/home/gc/wp3data/UD/31148_MRI_sMRI_400614.nii');
aap=aas_addinitialstream(aap,'epi','PUD400614','/home/gc/wp3data/UD/31147_MRI_rsMRI_400614.nii'); 
... but I think more detailed instructions/examples can be useful.

Best,
Giuseppe

**Comment by tiborauer** [comment]
Why do you simply do:
aap=aas_addsubject(aap,'PUD400614',{'/home/gc/wp3data/UD/31148_MRI_sMRI_400614.nii','/home/gc/wp3data/UD/31147_MRI_rsMRI_400614.nii'});

I recommend you typing:
help aas_addsubject
to see the documentation.

Vale,
Tibor

**Comment by giuseppecabras** [comment]
Thanks Tibor,
I thought that for NIfTI input files, aas_addinitialstream was needed to specify the type of data stream (epi or structural) when more then one type are used by the recipe. But also, I see that in "fromnifti" recipes I need a special "fromnifti" module (like aamod_epifromnifti) which are not generally available. Some more example of "fromnifti" user scripts or a special documentation resource for NIfTI input data would be useful. 
Best,
Giuseppe

**Comment by tiborauer** [comment]
aamod_epifromnifti and aamod_structuralfromnifti are there
But you are right, we may need to update our example scipts.

**Comment by conorwild** [comment]
Hi Giuseppe,

There are a couple ways to accomplish what you want to do (starting with converted nifti images), and our documentation could really use some updating with the details.  I'll work on that!

You are correct in that you can use aas_addinitialstream() to import your epi and structural images. This is quite easy for the structural stream, and this should work for you:


but that way tends to get a little complicated for the epi stream because you would also need create and import a dicom_header stream (that contains information about the TR, TE, etc.). Luckily, this is all made easier

**Comment by tiborauer** [comment]
Hi Guiseppe,

I have updated the examples (in devel-share branch).
See examples/aa_user_fmri_fromnifti.m.

Vale,
Tibor
