### ISSUE TITLE
Error occur when reading tasklist using function aarecipe

### ISSUE THREAD

**Issue by gr8zhuzc** [rhodricusack/automaticanalysis#91]
I am using Matlab 2015b and the most current aa(version 4). This error occurs when I run the demo code. The original demo code uses "aap=aarecipe("aap_tasklist_fmri_noslicetiming_withmodel_firstlevel.xml")" but I found out there is no tasklist file named "aap_tasklist_fmri_noslicetiming_withmodel_firstlevel.xml" in the  #aa documents I cloned so I changed it to a random tasklist that exits. The problem is that no matter what tasklist xml file I use, the same errors occur. 

"Assignment between unlike types is not allowed.

Error in aarecipe>processbranch (line 217)
                newStages.module(dependI) = arrayfun(@(x) setfield(x, 'tobecompletedfirst',
                x.tobecompletedfirst+length(outstages.module)), newStages.module(dependI));

Error in aarecipe (line 51)
    aap.tasklist.main=processbranch(aap,aap.directory_conventions.analysisid_suffix,'*',aap.tasklist.main,1);

Error in aa_user_demo_v1 (line 9)
aap = aarecipe('aap_tasklist_fmri.xml');"

**Comment by tiborauer** [comment]
Hi,

I am sorry for that the update might have caused you trouble. I have now updated both aa v4.3 (aka branch "devel-share") and aa v5.0 (aka branch "v5"), so both have exmple UMS (aa_user_demo_v2.m) and corresponding tasklist (aap_tasklist_demo.xml) to analyse the demo dataset. Please, used them instead of those shiped with the dataset when using either of these two branches!

**Comment by jpeelle** [comment]
Hi Tibor,

We've tried using devel-share as you suggest, and different versions of tasklists, but are still getting the type mismatch error. It seems to have trouble because there are no dependencies so dependI is empty ([]).

We are using Matlab 2015b and have tried both aa4 and aa5.

Unfortunately I don't understand all of the aarecipe code so I'm stuck on debugging this.

Any other thoughts?

**Comment by tiborauer** [comment]
It must be something MATLAB-specific, then. Unfortunately, I have no access to MATLAB 2015b. I have tested MATLABs between 2009a and 2015a.
I mostly use 2012b, because MatWorks has changed parallel computing dependency checks since then, and it causes serious lags when processing SPM (sub)folders for dependencies.

**Comment by conorwild** [comment]
I have submitted a fix for this bug to the devel-share branch. The issue was caused by a small change in Matlab2015b; specifically, how arrayfun() works with struct arrays. Hopefully it works for you all now -  please try it out!

**Comment by tiborauer** [comment]
It works for me (2012b). How about you, @jpeelle and @gr8zhuzc?

**Comment by gr8zhuzc** [comment]
Thank you Tibor and Conor, we have transferred our work to a 2014b matlab so that issue is solved. I didn't try the new version on the Matlab 2015b, Conor, but hopefully it should work out. To clarify, I am a student in Dr. Peelle's lab. Thank you again.

**Comment by tiborauer** [comment]
Thank you for spotting this issue!
And welcome to the aa-world!

Vale,

Auer, Tibor M.D. Ph.D.
MRC Cognition and Brain Sciences Unit
15 Chaucer Road
Cambridge
CB2 7EF
United Kingdom
Phone/Work: +44-(0)1223-273613
Mail: Tibor.Auer@mrc-cbu.cam.ac.uk
________________________________
